---

version: "3.7"

services:
  app:
    command: ["bash", "-c", "digdag scheduler"]
    tty: true
    working_dir: /app
    image: my-digdag
    build:
      context: .
      dockerfile: Dockerfile.digdag
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
