FROM adoptopenjdk:11-jre-openj9-bionic

RUN apt-get update && apt-get install -y tzdata

RUN curl -o /usr/local/bin/digdag --create-dirs -L "https://dl.digdag.io/digdag-latest" \
  && chmod +x /usr/local/bin/digdag
