---

version: "3.7"

services:
  app:
    command: ["./sample.sh"]
    working_dir: /app
    image: debian:buster-slim
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
    tty: false
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: "docker.{{.ImageName}}.{{.Name}}.{{.ID}}"
    links:
      - fluentd
  fluentd:
    image: my-fluentd
    build:
      context: .
      dockerfile: Dockerfile.fluentd
    volumes:
      - ./log:/fluentd/log
      - ./fluent.conf:/fluentd/etc/fluent.conf:ro
    ports:
      - 24224:24224
    environment:
      TZ: Asia/Tokyo
      SLACK_URL: $SLACK_URL
